name: Auto Spotless Apply

on:
  push:
    branches: [ '**' ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: tools platform-tools platforms;android-33 :contentReference[oaicite:4]{index=4}

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties :contentReference[oaicite:5]{index=5}

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew :contentReference[oaicite:6]{index=6}

      - name: Apply Spotless Formatting
        run: ./gradlew spotlessApply

      - name: Commit & Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "style: ✨ auto-apply spotless"
          push: true
